In [3]:
from pathlib import Path

import pandas as pd
import matplotlib.ticker as mtick

from src.reader import read_lusa, read_timebank

ROOT = Path().resolve().parent

## Prompt Selection

In [4]:
results_path = ROOT / "results" / "prompt_selection"

In [9]:
df_pt = pd.read_csv(results_path / "portuguese"/ "results.csv")
df_pt["language"] = "Portuguese"

df_en = pd.read_csv(results_path / "english"/ "results.csv")
df_en["language"] = "English"

df = pd.concat([df_pt, df_en])
df.reset_index(inplace=True, drop=True)

In [13]:
to_plot = df[["model", "template", "entity", "language", "f1"]]
print(to_plot)

              model     template            entity    language        f1
0           chatgpt      ext_exp    event triggers  Portuguese  0.317295
1           chatgpt          ext    event triggers  Portuguese  0.331579
2           chatgpt          cls    event triggers  Portuguese  0.379070
3           chatgpt      cls_exp    event triggers  Portuguese  0.410072
4           chatgpt  ext_def_exp    event triggers  Portuguese  0.452592
..              ...          ...               ...         ...       ...
376  llama2-7b-chat  cls_def_exp  time expressions     English  0.032432
377  llama2-7b-chat      ext_exp  time expressions     English  0.070270
378  llama2-7b-chat          ext  time expressions     English  0.070652
379  llama2-7b-chat  ext_def_exp  time expressions     English  0.118380
380  llama2-7b-chat      ext_def  time expressions     English  0.118380

[381 rows x 5 columns]

In [31]:
to_plot.groupby(["model", "template", "entity", "language"]).mean()

                                                           f1
model          template entity           language
chatgpt        cls      event triggers   English     0.339321
                                         Portuguese  0.379070
                        participants     Portuguese  0.191159
                        time expressions English     0.263804
                                         Portuguese  0.394558
...                                                       ...
llama2-7b-chat ext_exp  event triggers   English     0.064133
                                         Portuguese  0.034934
                        participants     Portuguese  0.105747
                        time expressions English     0.070270
                                         Portuguese  0.077121

[381 rows x 1 columns]

In [32]:
to_plot.groupby(["entity", "language", "template"]).mean("f1")

                                               f1
entity           language   template
event triggers   English    cls          0.117610
                            cls_def      0.096826
                            cls_def_exp  0.100079
                            cls_exp      0.120322
                            ext          0.052497
                            ext_def      0.104300
                            ext_def_exp  0.098714
                            ext_exp      0.053181
                 Portuguese cls          0.127442
                            cls_def      0.115902
                            cls_def_exp  0.121493
                            cls_exp      0.131735
                            ext          0.060636
                            ext_def      0.114655
                            ext_def_exp  0.111746
                            ext_exp      0.060961
participants     Portuguese cls          0.089373
                            cls_def      0.101725
                            cls_def_exp  0.101002
                            cls_exp      0.089539
                            ext          0.071431
                            ext_def      0.090701
                            ext_def_exp  0.091239
                            ext_exp      0.073143
time expressions English    cls          0.161693
                            cls_def      0.170661
                            cls_def_exp  0.170981
                            cls_exp      0.169233
                            ext          0.229087
                            ext_def      0.231129
                            ext_def_exp  0.230646
                            ext_exp      0.235521
                 Portuguese cls          0.187240
                            cls_def      0.185070
                            cls_def_exp  0.175436
                            cls_exp      0.181652
                            ext          0.257012
                            ext_def      0.273949
                            ext_def_exp  0.271718
                            ext_exp      0.294090

In [41]:
to_plot.groupby(["entity", "language", "template"]).mean("f1").unstack("template")

                                   f1                                  \
template                          cls   cls_def cls_def_exp   cls_exp
entity           language
event triggers   English     0.117610  0.096826    0.100079  0.120322
                 Portuguese  0.127442  0.115902    0.121493  0.131735
participants     Portuguese  0.089373  0.101725    0.101002  0.089539
time expressions English     0.161693  0.170661    0.170981  0.169233
                 Portuguese  0.187240  0.185070    0.175436  0.181652


template                          ext   ext_def ext_def_exp   ext_exp
entity           language
event triggers   English     0.052497  0.104300    0.098714  0.053181
                 Portuguese  0.060636  0.114655    0.111746  0.060961
participants     Portuguese  0.071431  0.090701    0.091239  0.073143
time expressions English     0.229087  0.231129    0.230646  0.235521
                 Portuguese  0.257012  0.273949    0.271718  0.294090

In [42]:
to_plot.groupby(["model", "language", "template"]).mean("f1").unstack("template")

                                  f1                                  \
template                         cls   cls_def cls_def_exp   cls_exp
model           language
chatgpt         English     0.301563  0.350961    0.365969  0.301149
                Portuguese  0.321595  0.370899    0.350555  0.312415
falcon-7b       Portuguese  0.000000  0.000000    0.000000  0.000000
gpt3            English     0.154656  0.132139    0.132490  0.161751
                Portuguese  0.266368  0.286933    0.269211  0.275862
gpt4            English     0.610016  0.494253    0.494067  0.649743
                Portuguese  0.410106  0.264610    0.276687  0.404509
llama2-13b      English     0.009539  0.000000    0.000000  0.009539
                Portuguese  0.008578  0.010650    0.010650  0.008578
llama2-13b-chat English     0.046526  0.048372    0.048372  0.046413
                Portuguese  0.082388  0.071630    0.071630  0.082388
llama2-70b      English     0.031129  0.038318    0.038839  0.030152
                Portuguese  0.069396  0.117619    0.130591  0.070914
llama2-70b-chat English     0.096720  0.123431    0.123816  0.097542
                Portuguese  0.168966  0.160460    0.157586  0.168966
llama2-7b       English     0.006711  0.000000    0.000000  0.006711
                Portuguese  0.001188  0.025910    0.025910  0.001188
llama2-7b-chat  English     0.000000  0.016216    0.016216  0.000000
                Portuguese  0.018265  0.033615    0.033615  0.018265


template                         ext   ext_def ext_def_exp   ext_exp
model           language
chatgpt         English     0.220568  0.332837    0.333036  0.243943
                Portuguese  0.305727  0.357072    0.350809  0.295945
falcon-7b       Portuguese  0.000000  0.000000    0.000000  0.000000
gpt3            English     0.189555  0.211054    0.210736  0.191727
                Portuguese  0.213911  0.210546    0.210723  0.220192
gpt4            English     0.394497  0.375876    0.342687  0.404880
                Portuguese  0.189536  0.187797    0.199180  0.206339
llama2-13b      English     0.006623  0.031141    0.031141  0.006623
                Portuguese  0.021505  0.107334    0.107334  0.021505
llama2-13b-chat English     0.116867  0.123269    0.123269  0.116867
                Portuguese  0.172449  0.176321    0.176321  0.172449
llama2-70b      English     0.103002  0.154324    0.160323  0.099293
                Portuguese  0.155082  0.162008    0.137027  0.174136
llama2-70b-chat English     0.168622  0.167258    0.167258  0.168622
                Portuguese  0.156593  0.158056    0.163144  0.156593
llama2-7b       English     0.000000  0.000000    0.000000  0.000000
                Portuguese  0.009524  0.038616    0.038616  0.009524
llama2-7b-chat  English     0.067393  0.113669    0.113669  0.067202
                Portuguese  0.072601  0.108617    0.108617  0.072601